
services:
  # bot:
  #   build: ./bot
  #   container_name: cryptocases_bot
  #   environment:
  #     - BOT_TOKEN=your_telegram_token
  #   depends_on:
  #     - backend
  #   restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cryptocases_api
    volumes:
      - ./backend/src:/app/src
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    restart: always

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    container_name: cryptocases_frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    restart: always

  mongo:
    image: mongo:6
    container_name: cryptocases_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
