

services:
  backend:
    # Беремо ті самі образи/збірку, що й для основного
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      # Спочатку тестове середовище, щоб воно могло перебити PROD-перемінні
      - ./backend/.env.test
      # Далі основне, якщо чогось не вистачає
      - ./backend/.env
    depends_on:
      - mongo
      - redis
    # entrypoint: ["/bin/sh", "-c"]
    # # Ось ця команда стартує pytest замість uvicorn
    # command: >
    #   python -m pytest --maxfail=1 --disable-warnings -vv --rootdir=/app --junitxml=/app/tests/results/junit.xml
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/tests/results:/app/tests/results
