
services:
  bot:
      build:
        context: ./bot
        dockerfile: Dockerfile
      container_name: cryptocases_bot
      env_file:
        - bot/.env
      volumes:
        - ./bot:/app
      depends_on:
        - frontend
      restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cryptocases_api
    env_file:
      - ./backend/.env
      - ./backend/.env.test
    volumes:
      - ./backend/:/app/
      - ./data:/app/data
      - ./scripts/collect_stats.py:/app/scripts/collect_stats.py
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - mongo
      - redis
    restart: always

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    container_name: cryptocases_frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    restart: always

  redis:
    image: redis:7-alpine
    container_name: cryptocases_redis
    # вмикаємо автентифікацію паролем
    env_file:
      - ./backend/.env 
    command: ["redis-server", "--requirepass", "123456789"]
      
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  mongo:
    image: mongo:6
    container_name: cryptocases_mongo
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
  redis_data:
